// app/components/Sections/VagasSection.jsx
"use client";

import { useState, useEffect } from "react";
import FiltroDeVagas from "../FiltroVagas/FiltroVagas";
import CardVagas from "../Cards/CardVagas";

export default function VagasSection() {
  const [filtros, setFiltros] = useState({
    tipoDeVaga: "1",
    areaProfissional: "1",
    cidade: "",
    estado: "",
    vaga: "",
  });

  const [vagas, setVagas] = useState([]);
  useEffect(() => {
    const mockVagas = [
        {
          id: "1",
          titulo: "Desenvolvedor Frontend",
          descricao: "Desenvolvimento de interfaces web",
          area: "Tecnologia",
          localizacao: "São Paulo",
          estado: "SP",
          horario: "09h às 18h",
          salario: "R$ 3.000,00",
          tipoDeVaga: "2",
          nivelEnsino: "4",
          areaProfissional: "2",
          atividades: ["Desenvolver interfaces", "Testar aplicações"],
          requisitos: ["React", "CSS", "JavaScript"],
        },
        {
          id: "2",
          titulo: "Estágio em Marketing",
          descricao: "Auxiliar nas redes sociais",
          area: "Marketing",
          localizacao: "Santo André",
          estado: "SP",
          horario: "08h às 14h",
          salario: "R$ 1.000,00",
          tipoDeVaga: "3",
          nivelEnsino: "3",
          areaProfissional: "3",
          atividades: ["Criar postagens", "Agendar conteúdo"],
          requisitos: ["Conhecimento em redes sociais"],
        },
        {
          id: "3",
          titulo: "Analista de Dados",
          descricao: "Análise de grandes volumes de dados",
          area: "Tecnologia",
          localizacao: "Belo Horizonte",
          estado: "MG",
          horario: "10h às 19h",
          salario: "R$ 4.500,00",
          tipoDeVaga: "2",
          nivelEnsino: "5",
          areaProfissional: "2",
          atividades: ["Analisar dados", "Criar relatórios"],
          requisitos: ["SQL", "Python", "Power BI"],
        },
        {
          id: "4",
          titulo: "Vendedor",
          descricao: "Atendimento ao cliente e vendas",
          area: "Comercial",
          localizacao: "Curitiba",
          estado: "PR",
          horario: "08h às 17h",
          salario: "R$ 2.000,00",
          tipoDeVaga: "2",
          nivelEnsino: "3",
          areaProfissional: "4",
          atividades: ["Atender clientes", "Fechar vendas"],
          requisitos: ["Boa comunicação", "Experiência em vendas"],
        },
        {
          id: "5",
          titulo: "Estágio em RH",
          descricao: "Auxílio no recrutamento e seleção",
          area: "Recursos Humanos",
          localizacao: "Porto Alegre",
          estado: "RS",
          horario: "09h às 15h",
          salario: "R$ 1.200,00",
          tipoDeVaga: "3",
          nivelEnsino: "4",
          areaProfissional: "5",
          atividades: ["Triagem de currículos", "Agendamento de entrevistas"],
          requisitos: ["Organização", "Boa comunicação"],
        },
        {
          id: "6",
          titulo: "Assistente Administrativo",
          descricao: "Suporte administrativo geral",
          area: "Administração",
          localizacao: "Recife",
          estado: "PE",
          horario: "08h às 17h",
          salario: "R$ 2.500,00",
          tipoDeVaga: "2",
          nivelEnsino: "4",
          areaProfissional: "6",
          atividades: ["Organizar documentos", "Atendimento telefônico"],
          requisitos: ["Organização", "Pacote Office"],
        },
        {
          id: "7",
          titulo: "Desenvolvedor Backend",
          descricao: "Desenvolvimento de APIs e serviços",
          area: "Tecnologia",
          localizacao: "Florianópolis",
          estado: "SC",
          horario: "09h às 18h",
          salario: "R$ 4.000,00",
          tipoDeVaga: "2",
          nivelEnsino: "5",
          areaProfissional: "2",
          atividades: ["Desenvolver APIs", "Manutenção de sistemas"],
          requisitos: ["Node.js", "Banco de dados", "API REST"],
        },
        {
          id: "8",
          titulo: "Estágio em Design Gráfico",
          descricao: "Apoio na criação de artes digitais",
          area: "Design",
          localizacao: "Campinas",
          estado: "SP",
          horario: "08h às 14h",
          salario: "R$ 1.100,00",
          tipoDeVaga: "3",
          nivelEnsino: "3",
          areaProfissional: "7",
          atividades: ["Criar artes", "Editar imagens"],
          requisitos: ["Adobe Photoshop", "Criatividade"],
        },
        {
          id: "9",
          titulo: "Enfermeiro",
          descricao: "Cuidados com pacientes em hospital",
          area: "Saúde",
          localizacao: "Fortaleza",
          estado: "CE",
          horario: "Plantão 12h",
          salario: "R$ 3.800,00",
          tipoDeVaga: "2",
          nivelEnsino: "6",
          areaProfissional: "4",
          atividades: ["Atender pacientes", "Administrar medicamentos"],
          requisitos: ["Registro no COREN", "Experiência hospitalar"],
        },
        {
          id: "10",
          titulo: "Analista Financeiro",
          descricao: "Análise e controle financeiro",
          area: "Finanças",
          localizacao: "Goiânia",
          estado: "GO",
          horario: "08h às 17h",
          salario: "R$ 4.200,00",
          tipoDeVaga: "2",
          nivelEnsino: "5",
          areaProfissional: "8",
          atividades: ["Analisar contas", "Gerar relatórios"],
          requisitos: ["Excel avançado", "Conhecimento financeiro"],
        },
        {
          id: "11",
          titulo: "Engenheiro Civil",
          descricao: "Projetos e supervisão de obras",
          area: "Engenharia",
          localizacao: "Brasília",
          estado: "DF",
          horario: "08h às 18h",
          salario: "R$ 6.000,00",
          tipoDeVaga: "2",
          nivelEnsino: "6",
          areaProfissional: "9",
          atividades: ["Projetar estruturas", "Supervisionar obras"],
          requisitos: ["CREA ativo", "Experiência em obras"],
        },
        {
          id: "12",
          titulo: "Estágio em Jornalismo",
          descricao: "Apoio na redação de notícias",
          area: "Comunicação",
          localizacao: "Salvador",
          estado: "BA",
          horario: "08h às 14h",
          salario: "R$ 1.000,00",
          tipoDeVaga: "3",
          nivelEnsino: "3",
          areaProfissional: "10",
          atividades: ["Redigir notícias", "Cobertura de eventos"],
          requisitos: ["Boa redação", "Interesse por jornalismo"],
        },
        {
          id: "13",
          titulo: "Técnico de Segurança",
          descricao: "Inspeção e prevenção de riscos",
          area: "Segurança",
          localizacao: "Manaus",
          estado: "AM",
          horario: "07h às 16h",
          salario: "R$ 3.200,00",
          tipoDeVaga: "2",
          nivelEnsino: "4",
          areaProfissional: "11",
          atividades: ["Inspecionar locais", "Elaborar relatórios"],
          requisitos: ["NR-35", "Experiência na área"],
        },
        {
          id: "14",
          titulo: "Auxiliar de Cozinha",
          descricao: "Preparação e limpeza",
          area: "Gastronomia",
          localizacao: "Natal",
          estado: "RN",
          horario: "14h às 22h",
          salario: "R$ 1.200,00",
          tipoDeVaga: "2",
          nivelEnsino: "2",
          areaProfissional: "12",
          atividades: ["Preparar alimentos", "Limpar cozinha"],
          requisitos: ["Organização", "Agilidade"],
        },
        {
          id: "15",
          titulo: "Gerente de Loja",
          descricao: "Gestão de equipe e vendas",
          area: "Comercial",
          localizacao: "João Pessoa",
          estado: "PB",
          horario: "09h às 18h",
          salario: "R$ 3.800,00",
          tipoDeVaga: "2",
          nivelEnsino: "5",
          areaProfissional: "4",
          atividades: ["Gerenciar equipe", "Controlar estoque"],
          requisitos: ["Liderança", "Experiência em vendas"],
        },
        {
          id: "16",
          titulo: "Analista de Marketing Digital",
          descricao: "Campanhas online e SEO",
          area: "Marketing",
          localizacao: "Ribeirão Preto",
          estado: "SP",
          horario: "08h às 17h",
          salario: "R$ 3.500,00",
          tipoDeVaga: "2",
          nivelEnsino: "5",
          areaProfissional: "3",
          atividades: ["Criar campanhas", "Otimizar SEO"],
          requisitos: ["Google Ads", "SEO", "Analytics"],
        },
        {
          id: "17",
          titulo: "Programador Mobile",
          descricao: "Desenvolvimento de apps iOS e Android",
          area: "Tecnologia",
          localizacao: "Campina Grande",
          estado: "PB",
          horario: "09h às 18h",
          salario: "R$ 4.200,00",
          tipoDeVaga: "2",
          nivelEnsino: "5",
          areaProfissional: "2",
          atividades: ["Criar apps", "Testar funcionalidades"],
          requisitos: ["Flutter", "React Native", "Dart"],
        },
        {
          id: "18",
          titulo: "Estágio em Administração",
          descricao: "Suporte em tarefas administrativas",
          area: "Administração",
          localizacao: "Cuiabá",
          estado: "MT",
          horario: "08h às 14h",
          salario: "R$ 1.100,00",
          tipoDeVaga: "3",
          nivelEnsino: "3",
          areaProfissional: "6",
          atividades: ["Organizar documentos", "Atendimento ao cliente"],
          requisitos: ["Organização", "Boa comunicação"],
        },
        {
          id: "19",
          titulo: "Técnico em Informática",
          descricao: "Suporte técnico e manutenção",
          area: "Tecnologia",
          localizacao: "Aracaju",
          estado: "SE",
          horario: "08h às 17h",
          salario: "R$ 2.800,00",
          tipoDeVaga: "2",
          nivelEnsino: "4",
          areaProfissional: "2",
          atividades: ["Manutenção de PCs", "Suporte a usuários"],
          requisitos: ["Hardware", "Windows", "Redes"],
        },
        {
          id: "20",
          titulo: "Professor de Inglês",
          descricao: "Aulas particulares e em grupo",
          area: "Educação",
          localizacao: "Maceió",
          estado: "AL",
          horario: "14h às 20h",
          salario: "R$ 2.500,00",
          tipoDeVaga: "2",
          nivelEnsino: "6",
          areaProfissional: "13",
          atividades: ["Preparar aulas", "Avaliar alunos"],
          requisitos: ["Inglês fluente", "Experiência docente"],
        },
        {
          id: "21",
          titulo: "Assistente de Logística",
          descricao: "Controle e distribuição de mercadorias",
          area: "Logística",
          localizacao: "São Luís",
          estado: "MA",
          horario: "08h às 17h",
          salario: "R$ 2.200,00",
          tipoDeVaga: "2",
          nivelEnsino: "4",
          areaProfissional: "14",
          atividades: ["Controlar estoque", "Organizar entregas"],
          requisitos: ["Organização", "Pacote Office"],
        },
        {
          id: "22",
          titulo: "Estágio em Direito",
          descricao: "Apoio em pesquisas jurídicas",
          area: "Jurídico",
          localizacao: "Vitória",
          estado: "ES",
          horario: "08h às 14h",
          salario: "R$ 1.200,00",
          tipoDeVaga: "3",
          nivelEnsino: "3",
          areaProfissional: "15",
          atividades: ["Pesquisar jurisprudência", "Auxiliar advogados"],
          requisitos: ["Cursando Direito", "Boa redação"],
        },
        {
          id: "23",
          titulo: "Consultor de Vendas",
          descricao: "Prospecção e negociação com clientes",
          area: "Comercial",
          localizacao: "Blumenau",
          estado: "SC",
          horario: "08h às 17h",
          salario: "R$ 3.000,00",
          tipoDeVaga: "2",
          nivelEnsino: "5",
          areaProfissional: "4",
          atividades: ["Prospecção", "Fechar vendas"],
          requisitos: ["Experiência comercial", "Boa comunicação"],
        },
        {
          id: "24",
          titulo: "Analista de Sistemas",
          descricao: "Análise e documentação de sistemas",
          area: "Tecnologia",
          localizacao: "São José",
          estado: "SC",
          horario: "09h às 18h",
          salario: "R$ 4.500,00",
          tipoDeVaga: "2",
          nivelEnsino: "5",
          areaProfissional: "2",
          atividades: ["Analisar requisitos", "Documentar sistemas"],
          requisitos: ["UML", "SQL", "Comunicação"],
        },
        {
          id: "25",
          titulo: "Técnico em Enfermagem",
          descricao: "Cuidados básicos aos pacientes",
          area: "Saúde",
          localizacao: "Caxias do Sul",
          estado: "RS",
          horario: "Plantão 12h",
          salario: "R$ 2.800,00",
          tipoDeVaga: "2",
          nivelEnsino: "4",
          areaProfissional: "4",
          atividades: ["Administrar medicamentos", "Auxiliar enfermagem"],
          requisitos: ["Curso técnico", "COREN ativo"],
        },
        {
          id: "26",
          titulo: "Designer UX/UI",
          descricao: "Design de interfaces e experiência do usuário",
          area: "Design",
          localizacao: "Londrina",
          estado: "PR",
          horario: "09h às 18h",
          salario: "R$ 4.200,00",
          tipoDeVaga: "2",
          nivelEnsino: "5",
          areaProfissional: "7",
          atividades: ["Criar wireframes", "Testar usabilidade"],
          requisitos: ["Figma", "Adobe XD", "Criatividade"],
        },
        {
          id: "27",
          titulo: "Estágio em Engenharia",
          descricao: "Suporte em projetos de engenharia",
          area: "Engenharia",
          localizacao: "Uberlândia",
          estado: "MG",
          horario: "08h às 14h",
          salario: "R$ 1.200,00",
          tipoDeVaga: "3",
          nivelEnsino: "3",
          areaProfissional: "9",
          atividades: ["Apoiar projetos", "Auxiliar em medições"],
          requisitos: ["Cursando engenharia", "Conhecimento básico"],
        },
        {
          id: "28",
          titulo: "Auxiliar de Produção",
          descricao: "Atividades em linha de produção",
          area: "Indústria",
          localizacao: "Contagem",
          estado: "MG",
          horario: "06h às 14h",
          salario: "R$ 1.600,00",
          tipoDeVaga: "2",
          nivelEnsino: "2",
          areaProfissional: "16",
          atividades: ["Montagem", "Inspeção"],
          requisitos: ["Agilidade", "Disponibilidade"],
        },
        {
          id: "29",
          titulo: "Coordenador de Projetos",
          descricao: "Gestão de equipes e prazos",
          area: "Administração",
          localizacao: "Joinville",
          estado: "SC",
          horario: "08h às 17h",
          salario: "R$ 5.500,00",
          tipoDeVaga: "2",
          nivelEnsino: "6",
          areaProfissional: "6",
          atividades: ["Gerenciar equipes", "Planejar prazos"],
          requisitos: ["PMP", "Experiência em coordenação"],
        },
        {
          id: "30",
          titulo: "Recepcionista",
          descricao: "Atendimento e controle de acesso",
          area: "Administração",
          localizacao: "Maringá",
          estado: "PR",
          horario: "08h às 17h",
          salario: "R$ 1.800,00",
          tipoDeVaga: "2",
          nivelEnsino: "3",
          areaProfissional: "6",
          atividades: ["Receber visitantes", "Atender telefone"],
          requisitos: ["Boa comunicação", "Organização"],
        },
        {
          id: "31",
          titulo: "Analista de RH",
          descricao: "Recrutamento e desenvolvimento",
          area: "Recursos Humanos",
          localizacao: "São Bernardo do Campo",
          estado: "SP",
          horario: "08h às 17h",
          salario: "R$ 4.000,00",
          tipoDeVaga: "2",
          nivelEnsino: "5",
          areaProfissional: "5",
          atividades: ["Recrutar", "Treinar funcionários"],
          requisitos: ["Experiência em RH", "Boa comunicação"],
        },
        {
          id: "32",
          titulo: "Técnico em Mecânica",
          descricao: "Manutenção de máquinas industriais",
          area: "Indústria",
          localizacao: "São José dos Campos",
          estado: "SP",
          horario: "07h às 16h",
          salario: "R$ 3.000,00",
          tipoDeVaga: "2",
          nivelEnsino: "4",
          areaProfissional: "16",
          atividades: ["Manutenção preventiva", "Reparos"],
          requisitos: ["Curso técnico", "Experiência"],
        },
        {
          id: "33",
          titulo: "Jornalista",
          descricao: "Cobertura jornalística e redação",
          area: "Comunicação",
          localizacao: "Cuiabá",
          estado: "MT",
          horario: "08h às 17h",
          salario: "R$ 3.500,00",
          tipoDeVaga: "2",
          nivelEnsino: "6",
          areaProfissional: "10",
          atividades: ["Escrever artigos", "Cobrir eventos"],
          requisitos: ["Boa redação", "Experiência"],
        },
        {
          id: "34",
          titulo: "Estágio em Psicologia",
          descricao: "Apoio no atendimento clínico",
          area: "Saúde",
          localizacao: "Campo Grande",
          estado: "MS",
          horario: "08h às 14h",
          salario: "R$ 1.000,00",
          tipoDeVaga: "3",
          nivelEnsino: "3",
          areaProfissional: "4",
          atividades: ["Apoiar atendimento", "Realizar anamnese"],
          requisitos: ["Cursando Psicologia", "Empatia"],
        },
        {
          id: "35",
          titulo: "Engenheiro Eletricista",
          descricao: "Projetos e manutenção elétrica",
          area: "Engenharia",
          localizacao: "Teresina",
          estado: "PI",
          horario: "08h às 18h",
          salario: "R$ 5.500,00",
          tipoDeVaga: "2",
          nivelEnsino: "6",
          areaProfissional: "9",
          atividades: ["Projetar sistemas elétricos", "Manutenção"],
          requisitos: ["CREA ativo", "Experiência"],
        },
        {
          id: "36",
          titulo: "Técnico em Contabilidade",
          descricao: "Auxílio em rotinas contábeis",
          area: "Finanças",
          localizacao: "Macapá",
          estado: "AP",
          horario: "08h às 17h",
          salario: "R$ 2.500,00",
          tipoDeVaga: "2",
          nivelEnsino: "4",
          areaProfissional: "8",
          atividades: ["Conferir documentos", "Organizar arquivos"],
          requisitos: ["Curso técnico", "Excel"],
        },
        {
          id: "37",
          titulo: "Estágio em Ciências Contábeis",
          descricao: "Apoio em rotinas contábeis",
          area: "Finanças",
          localizacao: "Rio Branco",
          estado: "AC",
          horario: "08h às 14h",
          salario: "R$ 1.100,00",
          tipoDeVaga: "3",
          nivelEnsino: "3",
          areaProfissional: "8",
          atividades: ["Organizar documentos", "Lançar dados"],
          requisitos: ["Cursando Ciências Contábeis", "Organização"],
        },
        {
          id: "38",
          titulo: "Auxiliar de Limpeza",
          descricao: "Manter áreas limpas e organizadas",
          area: "Serviços Gerais",
          localizacao: "Boa Vista",
          estado: "RR",
          horario: "07h às 16h",
          salario: "R$ 1.200,00",
          tipoDeVaga: "2",
          nivelEnsino: "1",
          areaProfissional: "17",
          atividades: ["Limpar ambientes", "Organizar materiais"],
          requisitos: ["Proatividade", "Organização"],
        },
        {
          id: "39",
          titulo: "Assistente de Marketing",
          descricao: "Auxílio em campanhas e redes sociais",
          area: "Marketing",
          localizacao: "Palmas",
          estado: "TO",
          horario: "08h às 17h",
          salario: "R$ 2.200,00",
          tipoDeVaga: "2",
          nivelEnsino: "4",
          areaProfissional: "3",
          atividades: ["Criar conteúdo", "Gerenciar redes sociais"],
          requisitos: ["Conhecimento em mídias sociais", "Criatividade"],
        },
        {
          id: "40",
          titulo: "Técnico em Edificações",
          descricao: "Apoio em projetos de construção",
          area: "Engenharia",
          localizacao: "São João del Rei",
          estado: "MG",
          horario: "08h às 17h",
          salario: "R$ 3.200,00",
          tipoDeVaga: "2",
          nivelEnsino: "4",
          areaProfissional: "9",
          atividades: ["Auxiliar em projetos", "Medições"],
          requisitos: ["Curso técnico", "Organização"],
        },
        {
          id: "41",
          titulo: "Analista de Suporte",
          descricao: "Suporte a usuários e sistemas",
          area: "Tecnologia",
          localizacao: "Vitória da Conquista",
          estado: "BA",
          horario: "08h às 17h",
          salario: "R$ 3.500,00",
          tipoDeVaga: "2",
          nivelEnsino: "5",
          areaProfissional: "2",
          atividades: ["Atender chamados", "Resolver problemas"],
          requisitos: ["Conhecimento em TI", "Boa comunicação"],
        },
        {
          id: "42",
          titulo: "Motorista",
          descricao: "Transporte de cargas e mercadorias",
          area: "Logística",
          localizacao: "Piracicaba",
          estado: "SP",
          horario: "07h às 16h",
          salario: "R$ 2.500,00",
          tipoDeVaga: "2",
          nivelEnsino: "2",
          areaProfissional: "14",
          atividades: ["Transportar cargas", "Manutenção básica do veículo"],
          requisitos: ["CNH categoria D", "Experiência"],
        },
        {
          id: "43",
          titulo: "Consultor de Recursos Humanos",
          descricao: "Planejamento e desenvolvimento de pessoas",
          area: "Recursos Humanos",
          localizacao: "Feira de Santana",
          estado: "BA",
          horario: "08h às 17h",
          salario: "R$ 4.500,00",
          tipoDeVaga: "2",
          nivelEnsino: "6",
          areaProfissional: "5",
          atividades: ["Desenvolver treinamentos", "Avaliar desempenho"],
          requisitos: ["Experiência em RH", "Boa comunicação"],
        },
        {
          id: "44",
          titulo: "Analista de Marketing",
          descricao: "Planejamento e execução de campanhas",
          area: "Marketing",
          localizacao: "São Carlos",
          estado: "SP",
          horario: "08h às 17h",
          salario: "R$ 3.800,00",
          tipoDeVaga: "2",
          nivelEnsino: "5",
          areaProfissional: "3",
          atividades: ["Planejar campanhas", "Analisar resultados"],
          requisitos: ["Excel", "Marketing digital"],
        },
        {
          id: "45",
          titulo: "Técnico em Telecomunicações",
          descricao: "Instalação e manutenção de redes",
          area: "Tecnologia",
          localizacao: "Campina Grande",
          estado: "PB",
          horario: "08h às 17h",
          salario: "R$ 3.000,00",
          tipoDeVaga: "2",
          nivelEnsino: "4",
          areaProfissional: "2",
          atividades: ["Instalar equipamentos", "Manutenção de redes"],
          requisitos: ["Experiência na área", "Curso técnico"],
        },
        {
          id: "46",
          titulo: "Assistente Financeiro",
          descricao: "Controle de contas e pagamentos",
          area: "Finanças",
          localizacao: "Cascavel",
          estado: "PR",
          horario: "08h às 17h",
          salario: "R$ 2.800,00",
          tipoDeVaga: "2",
          nivelEnsino: "4",
          areaProfissional: "8",
          atividades: ["Conferir contas", "Realizar pagamentos"],
          requisitos: ["Excel", "Organização"],
        },
        {
          id: "47",
          titulo: "Estágio em Comunicação Social",
          descricao: "Apoio em produção de conteúdo",
          area: "Comunicação",
          localizacao: "Aracaju",
          estado: "SE",
          horario: "08h às 14h",
          salario: "R$ 1.000,00",
          tipoDeVaga: "3",
          nivelEnsino: "3",
          areaProfissional: "10",
          atividades: ["Produzir conteúdo", "Gerenciar redes sociais"],
          requisitos: ["Boa redação", "Criatividade"],
        },
        {
          id: "48",
          titulo: "Auxiliar de Escritório",
          descricao: "Apoio administrativo geral",
          area: "Administração",
          localizacao: "Serra",
          estado: "ES",
          horario: "08h às 17h",
          salario: "R$ 1.800,00",
          tipoDeVaga: "2",
          nivelEnsino: "3",
          areaProfissional: "6",
          atividades: ["Organizar arquivos", "Atendimento ao cliente"],
          requisitos: ["Organização", "Boa comunicação"],
        },
        {
          id: "49",
          titulo: "Copeiro",
          descricao: "Serviço de copa e apoio",
          area: "Serviços Gerais",
          localizacao: "Mossoró",
          estado: "RN",
          horario: "07h às 16h",
          salario: "R$ 1.300,00",
          tipoDeVaga: "2",
          nivelEnsino: "1",
          areaProfissional: "17",
          atividades: ["Preparar bebidas", "Limpar copa"],
          requisitos: ["Organização", "Proatividade"],
        },
        {
          id: "50",
          titulo: "Consultor Técnico",
          descricao: "Atendimento técnico ao cliente",
          area: "Comercial",
          localizacao: "Juiz de Fora",
          estado: "MG",
          horario: "08h às 17h",
          salario: "R$ 3.800,00",
          tipoDeVaga: "2",
          nivelEnsino: "5",
          areaProfissional: "4",
          atividades: ["Atender clientes", "Resolver dúvidas técnicas"],
          requisitos: ["Conhecimento técnico", "Boa comunicação"],
        }
      ];
      

  
    setVagas(mockVagas);
  }, []);
  const aplicarFiltros = (filtrosAtualizados) => {
    setFiltros(filtrosAtualizados);
  };

  const vagasFiltradas = vagas.filter((vaga) => {
    const tipoOK = filtros.tipoDeVaga === "1" || vaga.tipoDeVaga === filtros.tipoDeVaga;
    const areaOK = filtros.areaProfissional === "1" || vaga.areaProfissional === filtros.areaProfissional;
    const cidadeOK = !filtros.cidade || vaga.localizacao.toLowerCase().includes(filtros.cidade.toLowerCase());
    const estadoOK = !filtros.estado || (vaga.estado && vaga.estado.toLowerCase().includes(filtros.estado.toLowerCase()));
    const vagaOK = !filtros.vaga || vaga.titulo.toLowerCase().includes(filtros.vaga.toLowerCase());
  
    return tipoOK && areaOK && cidadeOK && estadoOK && vagaOK;
  });
  

  return (
    <>
      <FiltroDeVagas filtros={filtros} onAplicarFiltros={aplicarFiltros} />
      <CardVagas vagas={vagasFiltradas} />
    </>
  );
}
